import { PARTS, SOURCES, DEVICE, CATEGORIES, searchParts } from './catalog.js';
import { buildModel, buildStage } from './geometry.js';
import { Renderer } from './renderer.js';
import { mix, modelMatrix, inventoryLayout, transform, sub, clamp } from './math.js';

const icons={layers:'<path d="m3 7 9-5 9 5-9 5zM3 12l9 5 9-5M3 17l9 5 9-5"/>',rotate:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-1l2 6M4 12l2 6a7 7 0 0 0 12-1"/>',reset:'<path d="M3 4v6h6"/><path d="M4 10a8 8 0 1 1 1 8"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',arrow:'<path d="M7 17 17 7M7 7h10v10"/>',expand:'<path d="M8 3H3v5M16 3h5v5M21 16v5h-5M3 16v5h5"/>',camera:'<path d="M3 7h5l2-3h4l2 3h5v13H3z"/><circle cx="12" cy="13" r="4"/>',tag:'<path d="M3 3h8l10 10-8 8L3 11Z"/><circle cx="7" cy="7" r="1"/>',grid:'<path d="M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z"/>'};
const svg=name=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${icons[name]}</svg>`;
const $=s=>document.querySelector(s);
$('#app').innerHTML=`
 <header class="topbar"><a class="brand" href="./" aria-label="Astra Explosion home"><span class="brand-icon">${svg('layers')}</span><span>ASTRA<span class="brand-light"> / EXPLOSION</span></span></a><span class="edition">INTERACTIVE OBJECTS <b>— 001</b></span><nav><button id="sources-open" class="text-button">About & sources ${svg('arrow')}</button><button id="library-open" class="text-button">Parts <span class="pill">24</span></button><a class="repo-link" href="https://github.com/Nuos/astra-explosion" target="_blank" rel="noopener noreferrer">GitHub ${svg('arrow')}</a></nav></header>
 <main class="workspace"><section id="exhibit" aria-label="Interactive iPhone exhibit">
  <div class="intro"><p class="eyebrow">THE ANATOMY OF AN EVERYDAY OBJECT</p><h1>iPhone 17 Pro<span class="title-dot">.</span></h1><p>A familiar form. An extraordinary assembly.</p></div>
  <div class="view-buttons" role="group" aria-label="Camera views"><button data-view="hero" class="active" title="Three-quarter rear view">3D</button><button data-view="front">Front</button><button data-view="rear">Rear</button></div>
  <div id="viewport"><canvas id="canvas" tabindex="0" aria-label="3D iPhone. Drag to orbit, scroll or pinch to zoom. Select components using the parts library."></canvas><div id="labels"></div><div id="loading"><span class="loader"></span><p>Assembling the exhibit…</p></div><div id="error" hidden><h2>Graphics unavailable</h2><p id="error-text"></p><button id="reload">Reload exhibit</button></div></div>
  <div class="stage-meta"><span id="mode-index">01 / ASSEMBLED</span><span id="visible-count">24 / 24 assemblies</span></div>
  <div class="finish"><span id="finish-label">Silver</span><div role="group" aria-label="Device finish"><button data-finish="silver" class="swatch silver active" aria-label="Silver" aria-pressed="true"></button><button data-finish="orange" class="swatch orange" aria-label="Cosmic Orange" aria-pressed="false"></button><button data-finish="blue" class="swatch blue" aria-label="Deep Blue" aria-pressed="false"></button></div></div>
  <div class="control-dock"><div class="primary-controls"><button id="explode" class="primary" aria-pressed="false">${svg('layers')}<span>Explode view</span><kbd>SPACE</kbd></button><div class="range-control"><div><label for="separation">Separation</label><output id="separation-value" for="separation">0%</output></div><input id="separation" type="range" min="0" max="100" value="0" aria-label="Explosion separation"/></div><div class="mode-switch" role="group" aria-label="Exploded layout"><button id="layers-mode" class="active" aria-pressed="true" title="Layered explosion">${svg('layers')}</button><button id="inventory-mode" aria-pressed="false" title="Inventory of all visible parts">${svg('grid')}</button></div></div>
  <div class="secondary-controls"><span class="gesture-hint">Drag to orbit <i>·</i> Scroll to zoom <i>·</i> Click to inspect</span><div><button id="labels-toggle" class="icon-button" aria-label="Toggle part labels" aria-pressed="false" title="Part labels">${svg('tag')}</button><button id="rotate-toggle" class="icon-button" aria-label="Toggle turntable rotation" aria-pressed="false" title="Turntable">${svg('rotate')}</button><button id="capture" class="icon-button" aria-label="Download scene as PNG" title="Download PNG">${svg('camera')}</button><button id="reset" class="icon-button" aria-label="Reset exhibit" title="Reset · R">${svg('reset')}</button></div></div></div>
 </section>
 <div id="library-backdrop" hidden></div><aside id="library" aria-label="Component library"><div class="library-top"><div><p class="eyebrow">EXPLORE THE ASSEMBLY</p><h2>Component library <span class="pill">24</span></h2></div><button id="library-close" class="icon-button" aria-label="Close component library">${svg('close')}</button></div>
 <div class="search-wrap">${svg('search')}<input id="search" type="search" placeholder="Search parts / 搜索部件" aria-label="Search components" autocomplete="off"/><kbd>/</kbd></div><div class="filters" role="group" aria-label="Component category"><button data-category="all" class="active" aria-pressed="true">All</button>${Object.entries(CATEGORIES).map(([id,[name]])=>`<button data-category="${id}" aria-pressed="false">${name}</button>`).join('')}</div><div class="list-meta"><span id="result-count">24 parts</span><button id="show-all" class="text-button">Show all</button></div><div id="part-list" role="list" aria-label="Parts"></div>
 <section id="inspector" aria-label="Selected component details" aria-live="polite"></section>
 </aside></main>
 <footer class="footer"><span><i class="status-dot"></i><span id="ready-status">Building geometry</span></span><span>21 Apple-diagram assemblies + 3 illustrative groups</span><button id="accuracy-open">Reconstructed geometry. Not Apple CAD. ${svg('arrow')}</button></footer>
 <dialog id="about"><div class="dialog-head"><span class="eyebrow">PROVENANCE / SCOPE</span><button id="sources-close" class="icon-button" aria-label="Close sources">${svg('close')}</button></div><h2>A view inside.<br>Not a service manual.</h2><p>This independent educational exhibit reconstructs the <strong>iPhone 17 Pro</strong> from public Apple documentation. The 21 numbered assemblies correspond to Apple’s exploded-view legend. They are not a complete bill of materials.</p><div class="accuracy-note"><strong>What is measured, and what is inferred?</strong><p>The nominal enclosure envelope follows 71.9 × 150 × 8.75 mm. Internal dimensions, camera protrusions, flex routes, chip placement and fine details are simplified estimates. There are no Apple CAD assets in this project.</p></div><p><strong>A1–A3 are illustrative.</strong> The vapor chamber is welded into the enclosure; the MagSafe details belong with the rear assembly; the 12 displayed fasteners are representative, not an exhaustive screw map. The animation is not a removal sequence. Inventory tiles individually scale parts for readability.</p><p>The model is an eSIM-inspired reference, not a verified regional configuration. Physical-SIM assemblies and regional radio details are not represented. iPhone 18 Pro is not implemented in this version.</p><h3>Primary references</h3><div class="source-links">${Object.entries(SOURCES).map(([key,[title,url]])=>`<a href="${url}" target="_blank" rel="noopener noreferrer"><span>${title}</span>${svg('arrow')}</a>`).join('')}</div><p class="fine-print">Checked ${DEVICE.checked}. Human Atlas inspired part selection, search, isolation and explosion; its MIT pointer/tap helper is adapted with attribution. All phone geometry and textures are authored for this project. Apple and iPhone are trademarks of Apple Inc.; this project is not affiliated with or endorsed by Apple.</p><h3>Keyboard</h3><p class="shortcuts"><kbd>Space</kbd> explode / assemble <kbd>R</kbd> reset <kbd>/</kbd> search <kbd>Esc</kbd> leave inspection</p></dialog><div id="toast" role="status" aria-live="polite"></div>`;

const state={amount:0,target:0,layout:'layers',category:'all',query:'',selected:null,isolated:null,hidden:new Set(),labels:false};
let engine,models=[],layoutCache;const motion=matchMedia('(prefers-reduced-motion: reduce)');let reduced=motion.matches;motion.addEventListener('change',()=>{reduced=motion.matches;engine?.request();});
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2700);}
function showError(message){$('#loading').hidden=true;$('#error').hidden=false;$('#error-text').textContent=message;$('#ready-status').textContent='Graphics unavailable';}
$('#reload').onclick=()=>location.reload();
function showLibrary(open=true){$('#library').classList.toggle('open',open);$('#library-backdrop').hidden=!open;$('#library-open').setAttribute('aria-expanded',String(open));if(open)setTimeout(()=>$('#search').focus(),100);else if(innerWidth<850&&$('#library').contains(document.activeElement))$('#library-open').focus();}
$('#library-open').onclick=()=>showLibrary();$('#library-close').onclick=()=>showLibrary(false);$('#library-backdrop').onclick=()=>showLibrary(false);
function showSources(){if(!$('#about').open)$('#about').showModal();}
$('#sources-open').onclick=showSources;$('#accuracy-open').onclick=showSources;$('#sources-close').onclick=()=>$('#about').close();$('#about').addEventListener('click',e=>{if(e.target===$('#about')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function visible(p){return !state.hidden.has(p.id)&&(!state.isolated||state.isolated===p.id)&&(state.category==='all'||state.category===p.category);}
function rebuildInventory(){const candidates=models.filter(visible);layoutCache=inventoryLayout(candidates,engine?engine.width/engine.height:1.4);}
function drawList(){const parts=searchParts(state.query,state.category);$('#result-count').textContent=`${parts.length} ${parts.length===1?'part':'parts'}`;
 $('#part-list').innerHTML=parts.length?parts.map(p=>`<div class="part-row ${state.selected===p.id?'selected':''} ${state.hidden.has(p.id)?'muted':''}" role="listitem"><button class="part-main" data-select="${p.id}" aria-pressed="${state.selected===p.id}"><span class="part-number ${p.official?'':'extra'}">${p.number}</span><span class="part-name">${p.name.replace(' · illustrative','').replace(' · representative','')}<small>${p.zh}</small></span></button><button class="visibility-button" data-hide="${p.id}" aria-label="${state.hidden.has(p.id)?'Show':'Hide'} ${p.name}" aria-pressed="${!state.hidden.has(p.id)}" title="${state.hidden.has(p.id)?'Show':'Hide'} part">${svg('eye')}</button></div>`).join(''):'<div class="empty-results">No matching components.<br><small>Try “camera”, “battery”, “盖板” or “A19”.</small></div>';
 document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>selectPart(b.dataset.select));document.querySelectorAll('[data-hide]').forEach(b=>b.onclick=()=>{const id=b.dataset.hide;state.hidden.has(id)?state.hidden.delete(id):state.hidden.add(id);if(state.hidden.has(id)&&state.selected===id){state.selected=null;state.isolated=null;engine&&(engine.selected=null);drawInspector();}refresh();});
}
function drawInspector(){const p=PARTS.find(p=>p.id===state.selected),el=$('#inspector');
 if(!p){el.innerHTML=`<p class="eyebrow">THE REFERENCE OBJECT</p><div class="spec-pair"><div><b>150.0<span> mm</span></b><small>Height</small></div><div><b>71.9<span> mm</span></b><small>Width</small></div></div><p class="inspector-hint">Choose a component to inspect its role, isolate its geometry and open the source.</p><button class="model-note" id="inspector-about">${svg('layers')} 21 documented identities · 3 illustrative groups ${svg('arrow')}</button>`;$('#inspector-about').onclick=showSources;return;}
 const [source,url]=SOURCES[p.source];el.innerHTML=`<div class="inspection-heading"><span class="eyebrow">${p.official?'APPLE CALLOUT':'ILLUSTRATIVE GROUP'} / ${p.number}</span><button id="deselect" class="icon-button" aria-label="Clear selection">${svg('close')}</button></div><h3>${p.name}</h3><p class="component-zh">${p.zh}</p><p class="component-description">${p.description}</p><div class="inspection-actions"><button id="isolate" class="isolate-button" aria-pressed="${state.isolated===p.id}">${svg('expand')} ${state.isolated===p.id?'Exit isolation':'Isolate part'}</button><a href="${url}" target="_blank" rel="noopener noreferrer" title="${source}">Source ${svg('arrow')}</a></div><small class="confidence">${p.official?'Documented identity':'Illustrative subdivision'} · Estimated geometry</small>`;
 $('#deselect').onclick=()=>selectPart(null);$('#isolate').onclick=()=>{if(!engine)return;state.isolated=state.isolated===p.id?null:p.id;engine.autoRotate=false;refresh();if(state.isolated){const ext=p.id==='fasteners'?7:Math.max(...models.find(m=>m.id===p.id).bounds.max.map((x,i)=>x-models.find(m=>m.id===p.id).bounds.min[i]));const back=['camera','back-glass','magsafe','enclosure'].includes(p.id);engine.setView(back?Math.PI-.28:.28,.08,Math.max(2.4,ext*1.8*Math.max(1,.9/(engine.width/engine.height))),[0,3.95,0],reduced);}else fitView();};
}
function refresh(){drawList();drawInspector();rebuildInventory();syncControls();engine?.request();}
function selectPart(id){const wasIsolated=!!state.isolated;state.isolated=null;state.selected=id;engine&&(engine.selected=id);if(id){state.hidden.delete(id);const p=PARTS.find(p=>p.id===id);if(state.category!=='all'&&state.category!==p.category)state.category='all';if(state.amount<.05&&p.category!=='shell')setExplosion(1);toast(`${p.number} / ${p.name}`);}refresh();if(wasIsolated)fitView();}
function fitView(){if(!engine)return;engine.autoRotate=false;if(state.layout==='inventory'&&!state.isolated){rebuildInventory();const aspect=engine.width/engine.height,d=Math.max(layoutCache.height/(2*Math.tan(.32)),layoutCache.width/(2*Math.tan(.32)*aspect))*1.22;engine.setView(0,0,Math.max(10,d),[0,0,0],reduced);}else{const d=(state.target>.05?23.5:17.7)*Math.max(1,.88/(engine.width/engine.height));engine.setView(state.target>.05?.82:2.62,state.target>.05?.26:.18,d,[0,3.45,0],reduced);}}
function setExplosion(t){state.target=clamp(t,0,1);if(state.isolated){state.isolated=null;drawInspector();}if(state.layout==='inventory'&&t===0)state.layout='layers';syncControls();fitView();engine?.request();}
function syncControls(){
 $('#separation').value=String(Math.round(state.target*100));$('#separation-value').value=`${Math.round(state.target*100)}%`;
 $('#explode').setAttribute('aria-pressed',String(state.target>.5));$('#explode span').textContent=state.target>.5?'Assemble view':'Explode view';
 $('#layers-mode').classList.toggle('active',state.layout==='layers');$('#inventory-mode').classList.toggle('active',state.layout==='inventory');$('#layers-mode').setAttribute('aria-pressed',String(state.layout==='layers'));$('#inventory-mode').setAttribute('aria-pressed',String(state.layout==='inventory'));
 $('.finish').hidden=state.layout==='inventory';$('.stage-meta').hidden=state.layout==='inventory';$('#separation').disabled=state.layout==='inventory';$('#rotate-toggle').setAttribute('aria-pressed',String(!!engine?.autoRotate));$('#labels-toggle').setAttribute('aria-pressed',String(state.labels));
 $('#mode-index').textContent=state.isolated?'04 / ISOLATED':state.layout==='inventory'?'03 / INVENTORY':state.target>.05?'02 / EXPLODED':'01 / ASSEMBLED';$('#visible-count').textContent=`${models.filter(visible).length} / 24 assemblies`;
 document.querySelectorAll('[data-category]').forEach(b=>{const active=b.dataset.category===state.category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
}
$('#search').addEventListener('input',e=>{state.query=e.target.value;drawList();});
 document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;state.isolated=null;if(state.selected&&PARTS.find(p=>p.id===state.selected).category!==state.category&&state.category!=='all'){state.selected=null;engine&&(engine.selected=null);}refresh();fitView();});
$('#show-all').onclick=()=>{state.hidden.clear();state.isolated=null;state.category='all';state.query='';$('#search').value='';refresh();fitView();};
$('#explode').onclick=()=>setExplosion(state.target>.5?0:1);$('#separation').oninput=e=>setExplosion(Number(e.target.value)/100);
$('#layers-mode').onclick=()=>{state.layout='layers';state.isolated=null;refresh();fitView();};$('#inventory-mode').onclick=()=>{state.layout='inventory';state.target=1;state.isolated=null;state.labels=true;refresh();fitView();};
$('#labels-toggle').onclick=()=>{state.labels=!state.labels;syncControls();engine?.request();};
$('#rotate-toggle').onclick=()=>{if(!engine)return;engine.autoRotate=!engine.autoRotate;syncControls();engine.request();};
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(!engine)return;if(state.layout==='inventory'){state.layout='layers';refresh();}const name=b.dataset.view;engine.autoRotate=false;const d=(state.target>.05?25:15.4)*Math.max(1,.88/(engine.width/engine.height));engine.setView(name==='front'?0:name==='rear'?Math.PI:state.target>.05?.82:2.62,name==='hero'?.2:.035,d,[0,3.95,0],reduced);document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));});
 document.querySelectorAll('[data-finish]').forEach(b=>b.onclick=()=>{if(!engine)return;engine.finish=b.dataset.finish;$('#finish-label').textContent={silver:'Silver',orange:'Cosmic Orange',blue:'Deep Blue'}[engine.finish];document.querySelectorAll('[data-finish]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b));});engine.request();});
$('#capture').onclick=async()=>{if(!engine)return;try{const blob=await engine.snapshot();if(!blob)throw Error('PNG encoder unavailable');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`astra-iphone17pro-${state.layout}-${Math.round(state.target*100)}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('Scene saved as PNG');}catch(e){toast(`Export failed: ${e.message}`);}};
function reset(){state.target=0;state.layout='layers';state.category='all';state.query='';state.selected=null;state.isolated=null;state.hidden.clear();state.labels=false;$('#search').value='';if(engine){engine.selected=null;engine.autoRotate=false;engine.finish='silver';}document.querySelector('[data-finish="silver"]').click();document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='hero'));refresh();fitView();toast('Exhibit reset');}
$('#reset').onclick=reset;
 document.addEventListener('keydown',e=>{const typing=['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName);if($('#about').open)return;if(e.key==='Tab'&&innerWidth<850&&$('#library').classList.contains('open')){const controls=[...$('#library').querySelectorAll('button,input,a[href]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}return;}if(e.key==='Escape'){if(state.selected||state.isolated){state.selected=null;state.isolated=null;engine&&(engine.selected=null);refresh();fitView();}showLibrary(false);return;}if(typing)return;if(e.code==='Space'&&(document.activeElement===$('#canvas')||document.activeElement===document.body)){e.preventDefault();setExplosion(state.target>.5?0:1);}else if(e.key.toLowerCase()==='r'){reset();}else if(e.key==='/'){e.preventDefault();if(innerWidth<850)showLibrary();$('#search').focus();}});

function targetTransform(part){
 let pos=part.position.map((v,i)=>v+part.explode[i]*state.amount+(i===1?4.16:0)),rot=[0,0,0],s=1;
 if(state.isolated===part.id){pos=sub([0,3.95,0],part.center);}
 else if(state.layout==='inventory'){
  const cell=layoutCache.cells.find(c=>c.id===part.id);if(cell){const ext=part.bounds.max.map((v,i)=>v-part.bounds.min[i]);s=Math.min(2.85/Math.max(ext[0],ext[2],.1),3.1/Math.max(ext[1],.1),4);rot=[0,['camera','back-glass','magsafe','enclosure'].includes(part.id)?Math.PI:0,0];const rc=transform(modelMatrix([0,0,0],rot,s),part.center).slice(0,3);pos=sub([cell.x,cell.y+.2,0],rc);}
 }return {pos,rot,s};
}
function update(dt){const alpha=reduced?1:1-Math.exp(-dt*9);let moving=Math.abs(state.amount-state.target)>.0001;state.amount=mix(state.amount,state.target,alpha);
 for(const p of models){p.visible=visible(p);const t=targetTransform(p);p.currentPosition=p.currentPosition.map((v,i)=>{if(Math.abs(v-t.pos[i])>.0001)moving=true;return mix(v,t.pos[i],alpha);});p.currentRotation=p.currentRotation.map((v,i)=>{if(Math.abs(v-t.rot[i])>.0001)moving=true;return mix(v,t.rot[i],alpha);});if(Math.abs(p.currentScale-t.s)>.0001)moving=true;p.currentScale=mix(p.currentScale,t.s,alpha);p.matrix=modelMatrix(p.currentPosition,p.currentRotation,p.currentScale);}
 engine.showStage=!state.isolated&&state.layout==='layers';return moving;
}
function positionLabels(){const used=[];const sorted=[...models].sort((a,b)=>Number(b.id===state.selected)-Number(a.id===state.selected));for(const p of sorted){const el=p.label;const show=p.visible&&(state.labels&&(state.amount>.1||state.layout==='inventory')||p.id===state.selected);el.hidden=!show;if(!show)continue;
 let point;if(state.layout==='inventory'&&!state.isolated){const c=layoutCache.cells.find(c=>c.id===p.id);point=[c.x,c.y-1.58,0];}else point=transform(p.matrix,[p.center[0],p.bounds.max[1]+.13,p.center[2]]).slice(0,3);
 const v=engine.screen(point),tileWidth=state.layout==='inventory'?Math.abs(engine.screen([point[0]+1.9,point[1],0]).x-engine.screen([point[0]-1.9,point[1],0]).x):0,full=(state.layout==='inventory'&&tileWidth>100)||state.selected===p.id;el.classList.toggle('full',full);el.classList.toggle('picked',state.selected===p.id);const width=full?Math.min(165,p.name.length*5.5+34):33,height=25,left=v.x-width/2,top=v.y-height/2;
 if(!v.visible||left<2||left+width>engine.width-2||top<2||top+height>engine.height-2||(!full&&used.some(r=>Math.abs(r.x-v.x)<(r.w+width)/2+3&&Math.abs(r.y-v.y)<28))){el.hidden=true;continue;}el.style.left=`${v.x}px`;el.style.top=`${v.y}px`;el.style.maxWidth=`${width}px`;used.push({x:v.x,y:v.y,w:width});
 }}
// Expose read-only diagnostics for automation and reproducible browser tests.
window.astra={getState:()=>({ready:!!engine,renderer:engine?.software?'canvas2d':'webgl2',amount:state.amount,target:state.target,layout:state.layout,selected:state.selected,isolated:state.isolated,visible:models.filter(visible).map(p=>p.id),finish:engine?.finish,autoRotate:engine?.autoRotate,camera:engine?{...engine.camera,target:[...engine.camera.target]}:null,meshCount:models.reduce((s,p)=>s+p.meshes.length,0),triangles:models.reduce((s,p)=>s+p.meshes.reduce((n,m)=>n+m.vertices.length/24,0),0)}),projectPart:id=>{const p=models.find(p=>p.id===id);return p&&engine?engine.screen(transform(p.matrix,p.center).slice(0,3)):null;}};
 drawList();drawInspector();
 requestAnimationFrame(()=>{setTimeout(()=>{try{
  models=buildModel();for(const p of models){p.currentPosition=p.position.map((v,i)=>v+(i===1?4.16:0));p.currentRotation=[0,0,0];p.currentScale=1;p.matrix=modelMatrix(p.currentPosition);p.visible=true;const el=document.createElement('button');el.className='part-label';el.hidden=true;el.innerHTML=`<b>${p.number}</b><span>${p.name.replace(' · illustrative','').replace(' · representative','')}</span>`;el.title=p.name;el.setAttribute('aria-label',`Inspect ${p.name}`);el.onclick=()=>selectPart(p.id);$('#labels').append(el);p.label=el;}
  engine=new Renderer($('#canvas'),models,buildStage());engine.onSelect=selectPart;engine.onUpdate=update;engine.onRender=positionLabels;engine.onError=showError;engine.onInteract=()=>syncControls();engine.onResize=()=>{rebuildInventory();if(state.layout==='inventory'&&!state.isolated)fitView();};rebuildInventory();syncControls();fitView();engine.request();$('#loading').hidden=true;$('#ready-status').textContent=engine.software?'Live 3D / Software fallback':'Live 3D / WebGL 2';document.body.dataset.ready='true';
 }catch(e){showError(e.message);console.error(e.message);}},30);});
 window.addEventListener('pagehide',()=>engine?.dispose());
